import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import CatalogModal from "../components/Catalog/CatalogModal";
import ShoppingCartModal from "../components/(ShoppingCart)/ShoppingCartModal";
import CatalogModalMobile from "@/components/Catalog/CatalogModalMobile";
import Providers from "@/providers/Providers";
import AuthModal from "@/components/auth/AuthModal";

const roboto = Roboto({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Providers>
          <Navbar />
          {children}
          <ShoppingCartModal />
          <CatalogModal />
          <CatalogModalMobile />
          <AuthModal/>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
