import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import CatalogModal from "../components/CatalogModal";
import ShoppingCartModal from "../components/(ShoppingCart)/ShoppingCartModal";
import { getCategories } from "@/api";

const roboto = Roboto({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const categories = await getCategories();
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navbar />
        {children}
        <ShoppingCartModal/>
        <CatalogModal categories={categories}/>
        <Footer />
      </body>
    </html>
  );
}
